### ISSUE TITLE
Feeds not reverse-chronological (most recent on top) — IFTTT cannot read them

### ISSUE THREAD

**Issue by TimTCM** [usgpo/rss#10]
IFTTT cannot find new items in this feed because it's not in reverse-chronological order.

IFTTT only looks for new items at the top of the feed, and GovInfo does not put the most recent entries at the top of the feed.

Tim
16,054 days

**Comment by jonquandt** [comment]
Good evening,

Could you provide a little more context for your request? 

I tried creating an IFTTT applet triggering based off of new items in the BILLSTATUS individual bill feed to send an email with the contents of the individual item and let it run for several hours.

I am seeing new entries in the RSS feed triggering emails over multiple rounds of updates. See a screenshot below:

![image](https://user-images.githubusercontent.com/7905226/118910092-f4493680-b8f1-11eb-9e8d-0f6aae8420af.png)


Is there a particular feed that's you're interested in that we can review? It may be that IFTTT isn't firing frequently enough to catch all items if there are a large volume of documents coming in at once. Knowing which feed you are interested in can help with testing and potentially adjusting the number of items.

Depending on your use case, you may also be interested in looking at our sitemaps or API.

**Comment by llaplant** [comment]
@TimTCM following up on this to see if we can provide additional assistance.

**Comment by jonquandt** [comment]
Closing this issue as we cannot recreate and have not heard further feedback.

**Comment by TimTCM** [comment]
My request was specific to the CREC feed. That's the one IFTTT could never figure out when it had new content.
https://www.govinfo.gov/rss/crec.xml

My apologies for the long delay. I never noticed someone had replied. I think this is the first time someone has replied to me on GitHub.

Tim
16,468 days

**Comment by jonquandt** [comment]
@TimTCM - not a problem. Reopening the issue. I am creating a new RSS -> email test for the crec RSS feed and will monitor over the next few days

**Comment by jonquandt** [comment]
Ok, so it appears this isn't an issue with the order of the RSS feed. Rather, IFTTT is only pulling "new" articles based on checking for new items in the RSS since the last time IFTTT polled. 

You're right that CREC isn't triggering this and this is because our RSS feed is using the official dateIssued value instead of the date/time made available on govinfo. our dateIssued value only includes the date, so it's always going to be midnight of the day of issue - e.g. the 7/7/22 CREC issued this morning has a pubDate of 2022-07-07T00:00:00Z, which IFTTT won't be able to pick up on when the new item is added later in the morning in . 

I have a item in our backlog to address this now. I'm hoping to get this into our next release.

**Comment by TimTCM** [comment]
Good news. Thank you!

**Comment by jonquandt** [comment]
Following up on this -- we have made a change to how the pubDate element is filled in, which should allow IFTTT to pull it - now the pubDate is showing the time that the CREC was published on GovInfo instead of providing the issue date value without a time.

**Comment by TimTCM** [comment]
Thank you! My previously-archived IFTTT applet has successfully restarted. I plan to see how it works over the coming week.

Last weekend I also set up a pull of the daily CREC zip file, and that has worked well, too.

**Comment by jonquandt** [comment]
Closing this issue as it appears that it has been resolved.
